Ignore nil slider values, use row's min instead.
Attempting to set a UISlider's value to nil (done when calling
form.reset) causes the following exception:

TypeError: can't convert nil into Float

Instead, ignore nil values and use the row's range.min as a fallback.